import { ReactElement, useEffect } from 'react';
import Head from 'next/head'
import { Button, Typography } from '@mui/material'
import Layout from '../src/components/Layout';
import { useDispatch } from 'react-redux';
import { clientRenderState } from '../src/redux/test/testActions';


export default function Home() {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(clientRenderState())
  }, [dispatch])
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Typography variant="h4" component="h1" gutterBottom>
        심리테스트
      </Typography>
      <br />
      <Button sx={{ mb: 2 }} variant="contained" href="/test">테스트 시작하기</Button>
      <Button sx={{ mb: 2 }} variant="outlined" href="/create">나만의 테스트 만들기</Button>
      <Button variant="outlined" href="/show-redux-state">리덕스 상태 보기</Button>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}